### ISSUE TITLE
htcondor 8.5.2 and -allusers

### ISSUE THREAD

**Issue by dsschult** [dsschult/pyglidein#13]
HTCondor 8.5.2 changes the `condor_q` output to only show the current user's jobs.  A new flag `-allusers` is available to show everything.  We need to detect the condor version and apply this flag if version >= 8.5.2.

This should only affect `server.py`, as the client only needs to know about the current user anyway.

**Comment by briedel** [comment]
Is there more than one user on the server side? Are we planning to have users outside of simprod using the pyglidein queue?

**Comment by dsschult** [comment]
There's currently two users (me and simprod).  I wouldn't be surprised if Gonzalo opened it to users though.
