### ISSUE TITLE
prioritize gpus / other exotic resource requests

### ISSUE THREAD

**Issue by dsschult** [dsschult/pyglidein#16]
In a queue submitting both cpu and gpu jobs, we ideally want the gpu jobs to get queued first because those sites are more limited.  The same goes for high memory jobs, I suppose.

Figure out how to make this happen.

**Comment by briedel** [comment]
Since the client knows all the states, couldn't we just sort them accordingly?

**Comment by dsschult** [comment]
Sure.  You just have to define the right sorting algorithm.
